### ISSUE TITLE
Create an attractive UI of the app 

### ISSUE THREAD

**Issue by Aviace** [Club-TechBrewers/Calculator-App#2]
Changes expected in the `XML` file of the app

**Comment by jarvision-git** [comment]
I would like to work on this issue.

**Comment by Aviace** [comment]
@jarvision-git sure go ahead!!

**Comment by jarvision-git** [comment]
I have implemented a UI for the calculator. Please give me your review on how does it look.

I have created a drawable resource for the rounded buttons and giving a custom color to the button. I have also change the primary color value in themes.xml file.

If the UI looks good to u, let me know so i can issue a pull request.

PS: This is not present on my Github repo. I downloaded the code zip file locally and made this. If you give me green light, I'll fork this repo and issue a pull request.

![image](https://github.com/Club-TechBrewers/Calculator-App/assets/85576130/9aab62d8-6d38-44a5-9c6e-aec78f974b9b)

**Comment by Aviace** [comment]
Hey @jarvision-git thats pretty good UI you have designed!!
yes you can fork and the repo and issue a pull request.
Let me know here if you face any issues while creating a pull request.

**Comment by jarvision-git** [comment]
Can I know if you use Windows or Unix based OS so that i can effectively address the LF-CRLF issue.

**Comment by Aviace** [comment]
I use Windows OS and can you also explain me the issue of LF-CRLF? I mean what is the issue?

**Comment by jarvision-git** [comment]
While adding files to stage, 

I got this Warning 
![image](https://github.com/Club-TechBrewers/Calculator-App/assets/85576130/36ee49ab-7eb8-4467-b7bc-727de5b01e0d)


Basically in windows, the end of line is represented by CRLF while in unix based OS it is represented by LF. 
So if u face issue in accessing this(on unix OS), I will have to take additional steps to tackle this by first converting repo to contain LF only. 


But it seems since u use windows, it wont be an issue

**Comment by jarvision-git** [comment]
I have created a pull request.

Also, I'm very new to open source contributions.

**Comment by Aviace** [comment]
Well being new to this culture you surely did a valued contribution!!

**Comment by Aviace** [comment]
can I have your Linked In profile?

**Comment by jarvision-git** [comment]
Thank you for being such a nice mentor. 

Here's my linkedIn, would love to connect with u
[LinkedIn](https://www.linkedin.com/in/kushal-desai-054699254/)

Also, I want to improve the functionality of this app.
Should I raise a code issue explaining the same??

**Comment by Aviace** [comment]
Sure go ahead! I appreciate your enthusiasm
